---
name: 'CloudCostGH'
description: 'Get instant CloudFormation cost estimates in your Pull Requests. Analyze infrastructure cost changes before deployment.'
author: 'CloudCostGH'
branding:
  icon: 'dollar-sign'
  color: 'green'

inputs:
  api_key:
    description: 'CloudCost API key from your dashboard'
    required: true
  github_token:
    description: 'GitHub token for posting PR comments (usually secrets.GITHUB_TOKEN)'
    required: false
  node_version:
    description: 'Node.js version to use (auto-detects from .nvmrc or .node-version if not specified, defaults to lts/*)'
    required: false
    default: ''
  region:
    description: 'AWS region to price in'
    required: false
    default: 'us-east-1'
  usage_profile:
    description: 'Usage profile (small|med|large)'
    required: false
    default: 'small'
  analyzer_version:
    description: 'Analyzer release tag (e.g. v0.1.0)'
    required: false
    default: 'v0.1.0'
  comment_title:
    description: 'Heading for the PR comment'
    required: false
    default: 'Cloud Cost Impact'
  update_existing_comment:
    description: 'Update existing CloudCost comment if present'
    required: false
    default: 'true'
  enable_usage_reporting:
    description: 'Send a usage record to the backend after successful analysis'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Test log output
      shell: bash
      run: |
        echo "=========================================="
        echo "TEST LOG: CloudCost Action Starting"
        echo "=========================================="
        echo "Current time: $(date)"
        echo "Working directory: $(pwd)"
        echo "GitHub workspace: ${{ env.GITHUB_WORKSPACE }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner arch: ${{ runner.arch }}"
        echo "Node version will be detected next..."
        echo "=========================================="
    
    - name: Detect Node version file
      id: detect-node
      shell: bash
      run: |
        echo "Detecting Node version file..."
        if [ -f ".nvmrc" ]; then
          echo "Found .nvmrc file"
          echo "version-file=.nvmrc" >> $GITHUB_OUTPUT
        elif [ -f ".node-version" ]; then
          echo "Found .node-version file"
          echo "version-file=.node-version" >> $GITHUB_OUTPUT
        else
          echo "No Node version file found, will use default"
          echo "version-file=" >> $GITHUB_OUTPUT
        fi
        echo "Node version detection complete"

    - name: Set up Node.js (with version file)
      if: steps.detect-node.outputs.version-file != '' && inputs.node_version == ''
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ steps.detect-node.outputs.version-file }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Set up Node.js (explicit or default)
      if: steps.detect-node.outputs.version-file == '' || inputs.node_version != ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version || 'lts/*' }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install dependencies
      shell: bash
      run: |
        echo "Installing npm dependencies..."
        npm ci
        echo "Dependencies installed successfully"
        echo "Installing npm dependencies for action..."
        cd "$GITHUB_ACTION_PATH"
        npm i
        echo "Dependencies installed successfully"

    - name: Test log before running analysis
      shell: bash
      run: |
        echo "=========================================="
        echo "TEST LOG: About to run CloudCost analysis"
        echo "=========================================="
        echo "Current time: $(date)"
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Checking if $GITHUB_ACTION_PATH/dist/index.js exists..."
        if [ -f "$GITHUB_ACTION_PATH/dist/index.js" ]; then
          echo "✓ $GITHUB_ACTION_PATH/dist/index.js exists"
          echo "File size: $(stat -f%z $GITHUB_ACTION_PATH/dist/index.js 2>/dev/null || stat -c%s $GITHUB_ACTION_PATH/dist/index.js 2>/dev/null || echo 'unknown') bytes"
        else
          echo "✗ $GITHUB_ACTION_PATH/dist/index.js NOT FOUND"
        fi
        echo "Environment check:"
        echo "  GITHUB_TOKEN: $([ -n "${{ inputs.github_token }}" ] && echo 'SET' || echo 'NOT SET')"
        echo "  CLOUDCOST_API_KEY: $([ -n "${{ inputs.api_key }}" ] && echo 'SET' || echo 'NOT SET')"
        echo "=========================================="
    
    - name: Checking $GITHUB_ACTION_PATH/dist/index.js file
      shell: bash
      run: |
        echo "Action path is: $GITHUB_ACTION_PATH"
        echo "Checking $GITHUB_ACTION_PATH/dist/index.js file:"
        if [ -f "$GITHUB_ACTION_PATH/dist/index.js" ]; then
          echo "  File exists: YES"
          echo "  File size: $(stat -c%s "$GITHUB_ACTION_PATH/dist/index.js") bytes"
          echo "  SHA256: $(sha256sum "$GITHUB_ACTION_PATH/dist/index.js" | awk '{print $1}')"
          echo "  First 200 chars:"
          head -c 200 "$GITHUB_ACTION_PATH/dist/index.js" || true
          echo
        else
          echo "  File exists: NO"
          echo "Listing $GITHUB_ACTION_PATH:"
          ls -R "$GITHUB_ACTION_PATH" || true
        fi


    - name: Run CloudCost analysis
      shell: bash
      run: |
        echo "Starting CloudCost analysis script..."
        echo "Environment variables being passed:"
        echo "  GITHUB_TOKEN: $([ -n "$GITHUB_TOKEN" ] && echo 'SET' || echo 'NOT SET')"
        echo "  CLOUDCOST_API_KEY: $([ -n "$CLOUDCOST_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
        echo "  CLOUDCOST_REGION: $([ -n "$CLOUDCOST_REGION" ] && echo "$CLOUDCOST_REGION" || echo 'NOT SET')"
        echo "  CLOUDCOST_USAGE_PROFILE: $([ -n "$CLOUDCOST_USAGE_PROFILE" ] && echo "$CLOUDCOST_USAGE_PROFILE" || echo 'NOT SET')"
        echo "  CLOUDCOST_ANALYZER_VERSION: $([ -n "$CLOUDCOST_ANALYZER_VERSION" ] && echo "$CLOUDCOST_ANALYZER_VERSION" || echo 'NOT SET')"
        echo "  CLOUDCOST_COMMENT_TITLE: $([ -n "$CLOUDCOST_COMMENT_TITLE" ] && echo "$CLOUDCOST_COMMENT_TITLE" || echo 'NOT SET')"
        echo "  CLOUDCOST_UPDATE_EXISTING_COMMENT: $([ -n "$CLOUDCOST_UPDATE_EXISTING_COMMENT" ] && echo "$CLOUDCOST_UPDATE_EXISTING_COMMENT" || echo 'NOT SET')"
        echo "  CLOUDCOST_ENABLE_USAGE_REPORTING: $([ -n "$CLOUDCOST_ENABLE_USAGE_REPORTING" ] && echo "$CLOUDCOST_ENABLE_USAGE_REPORTING" || echo 'NOT SET')"
        echo "  APP_CONFIG: $([ -n "$APP_CONFIG" ] && echo 'SET ($APP_CONFIG)' || echo 'NOT SET')"
        echo "Checking $GITHUB_ACTION_PATH/dist/index.js file:"
        echo "  File exists: $([ -f "$GITHUB_ACTION_PATH/dist/index.js" ] && echo 'YES' || echo 'NO')"
        echo "  File size: $(stat -c%s "$GITHUB_ACTION_PATH/dist/index.js") bytes"
        echo "  SHA256: $(sha256sum "$GITHUB_ACTION_PATH/dist/index.js" | awk '{print $1}')"
        echo "  First 200 chars:"
        head -c 200 "$GITHUB_ACTION_PATH/dist/index.js" || true
        echo "----------------------------------------"
        echo "Running: node $GITHUB_ACTION_PATH/dist/index.js"
        node "$GITHUB_ACTION_PATH/dist/index.js"
        echo "----------------------------------------"
        echo "CloudCost analysis script completed"
        echo "----------------------------------------"
        echo
      env:
        # Pass the GitHub token input through to the Node script
        GITHUB_TOKEN: ${{ inputs.github_token }}
        # Pass the API key input through to the Node script
        CLOUDCOST_API_KEY: ${{ inputs.api_key }}
        # Pass the rest of the configurable inputs through to the Node script
        CLOUDCOST_REGION: ${{ inputs.region }}
        CLOUDCOST_USAGE_PROFILE: ${{ inputs.usage_profile }}
        CLOUDCOST_ANALYZER_VERSION: ${{ inputs.analyzer_version }}
        CLOUDCOST_COMMENT_TITLE: ${{ inputs.comment_title }}
        CLOUDCOST_UPDATE_EXISTING_COMMENT: ${{ inputs.update_existing_comment }}
        CLOUDCOST_ENABLE_USAGE_REPORTING: ${{ inputs.enable_usage_reporting }}
        # Note: APP_CONFIG should be set in the workflow step's env section if needed
        # Composite actions don't have direct access to job-level env variables
