name: CloudCostGH
description: "Get instant CloudFormation cost estimates in your Pull Requests. Analyze infrastructure cost changes before deployment."
branding:
  icon: 'lock'
  color: 'blue'

inputs:
  api_key:
    description: "License key from purchase"
    required: true
  github_token:
    description: "GITHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: node -v >/dev/null 2>&1 || { echo "Node 18+ required"; exit 1; }

    # 1) Paywall
    - name: Verify license
      shell: bash
      env:
        YOUR_API_KEY: ${{ inputs.api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
      run: node $GITHUB_ACTION_PATH/verify-license.js "$REPO" "$SHA"

    # 2) Ensure we can diff against base branch
    - name: Fetch base branch
      shell: bash
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/${GITHUB_BASE_REF}:refs/remotes/origin/${GITHUB_BASE_REF}

    # 3) Collect CFN diffs (base vs head) for changed files
    - name: Collect CFN diff payload
      id: collect
      shell: bash
      env:
        BASE_REF: ${{ github.base_ref }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
      run: |
        node "$GITHUB_ACTION_PATH/scripts/collect-cfn-diff.js" \
          origin/${BASE_REF} \
          > cfn_diff_payload.json.gz
        echo "payload=cfn_diff_payload.json.gz" >> "$GITHUB_OUTPUT"

    # 4) Send to backend → get back Markdown
    - name: Request estimate
      id: estimate
      shell: bash
      env:
        YOUR_API_KEY: ${{ inputs.api_key }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        SHA: ${{ github.sha }}
        PAYLOAD_GZ: ${{ steps.collect.outputs.payload }}
      run: |
        node "$GITHUB_ACTION_PATH/scripts/run-estimator-cfn.js" \
          "$PAYLOAD_GZ" > cloudcost_comment.md
        echo "comment=cloudcost_comment.md" >> "$GITHUB_OUTPUT"

    # 5) Post (or update) PR comment
    - name: Post PR comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        COMMENT_MD: ${{ steps.estimate.outputs.comment }}
      run: node "$GITHUB_ACTION_PATH/scripts/post-markdown.js"
