---
name: 'CloudCostGH'
description: 'Get instant CloudFormation cost estimates in your Pull Requests. Analyze infrastructure cost changes before deployment.'
author: 'CloudCostGH'
branding:
  icon: 'dollar-sign'
  color: 'green'

inputs:
  api_key:
    description: 'CloudCost API key from your dashboard'
    required: true
  github_token:
    description: 'GitHub token for posting PR comments (usually secrets.GITHUB_TOKEN)'
    required: false
  node_version:
    description: 'Node.js version to use (auto-detects from .nvmrc or .node-version if not specified, defaults to lts/*)'
    required: false
    default: ''
  region:
    description: 'AWS region to price in'
    required: false
    default: 'us-east-1'
  usage_profile:
    description: 'Usage profile (small|med|large)'
    required: false
    default: 'small'
  analyzer_version:
    description: 'Analyzer release tag (e.g. v0.1.0)'
    required: false
    default: 'v0.1.0'
  comment_title:
    description: 'Heading for the PR comment'
    required: false
    default: 'Cloud Cost Impact'
  update_existing_comment:
    description: 'Update existing CloudCost comment if present'
    required: false
    default: 'true'
  enable_usage_reporting:
    description: 'Send a usage record to the backend after successful analysis'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Detect Node version file
      id: detect-node
      shell: bash
      run: |
        if [ -f ".nvmrc" ]; then
          echo "version-file=.nvmrc" >> $GITHUB_OUTPUT
        elif [ -f ".node-version" ]; then
          echo "version-file=.node-version" >> $GITHUB_OUTPUT
        else
          echo "version-file=" >> $GITHUB_OUTPUT
        fi

    - name: Set up Node.js (with version file)
      if: steps.detect-node.outputs.version-file != '' && inputs.node_version == ''
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ steps.detect-node.outputs.version-file }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Set up Node.js (explicit or default)
      if: steps.detect-node.outputs.version-file == '' || inputs.node_version != ''
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version || 'lts/*' }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run CloudCost analysis
      run: node dist/index.js
      shell: bash
      env:
        # Pass the GitHub token input through to the Node script
        GITHUB_TOKEN: ${{ inputs.github_token }}
        # Pass the API key input through to the Node script
        CLOUDCOST_API_KEY: ${{ inputs.api_key }}
